
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Sintatica.Teste;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTH = 32;
  public static final int CHAR = 8;
  public static final int CHARL = 35;
  public static final int INT = 7;
  public static final int MINUS = 3;
  public static final int LCHA = 13;
  public static final int SETOP = 15;
  public static final int NOT = 27;
  public static final int AND = 25;
  public static final int RPAR = 12;
  public static final int VIRG = 4;
  public static final int OR = 26;
  public static final int DIV = 23;
  public static final int PLUS = 21;
  public static final int IF = 17;
  public static final int PVIRG = 5;
  public static final int ID = 6;
  public static final int EOF = 0;
  public static final int RETURN = 20;
  public static final int error = 1;
  public static final int MOD = 24;
  public static final int VOID = 37;
  public static final int EQ = 28;
  public static final int TIMES = 22;
  public static final int MEQ = 31;
  public static final int ELSE = 18;
  public static final int INTL = 34;
  public static final int RCHA = 14;
  public static final int WHILE = 16;
  public static final int FLOAT = 9;
  public static final int LEQ = 30;
  public static final int LPAR = 11;
  public static final int PROC = 10;
  public static final int DIFF = 29;
  public static final int MTH = 33;
  public static final int VAR = 2;
  public static final int PRINT = 19;
  public static final int FLOATL = 36;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VAR",
  "MINUS",
  "VIRG",
  "PVIRG",
  "ID",
  "INT",
  "CHAR",
  "FLOAT",
  "PROC",
  "LPAR",
  "RPAR",
  "LCHA",
  "RCHA",
  "SETOP",
  "WHILE",
  "IF",
  "ELSE",
  "PRINT",
  "RETURN",
  "PLUS",
  "TIMES",
  "DIV",
  "MOD",
  "AND",
  "OR",
  "NOT",
  "EQ",
  "DIFF",
  "LEQ",
  "MEQ",
  "LTH",
  "MTH",
  "INTL",
  "CHARL",
  "FLOATL",
  "VOID"
  };
}

