package AnalisadorLexico;

public enum Token {
	ERROR,ID,NUMERO,SIMBOLO_ESPECIAL
	,OP_RELACIONAL,OP_ARITMETICO,
	NUMERO_DECIMAL,OP_LOGICO_OR,
	OP_LOGICO_AND,OP_LOGICO_NOT,
	COMENTARIO,OP_ATRIBUICAO, 
	PR_IF,PR_INT,
	PR_VAR,PR_ELSE,
	PR_CHAR,PR_VOID,PR_PRNT,
	PR_PROC,PR_FLOAT,
	PR_WHILE,PR_RETURN, LINHA,PR_MAIN,VIRGULA,OP_MENOR,
	OP_MAIOR, OP_IGUAL, OP_ADD, OP_SUB, OP_MULT, OP_DIV,
	OP_PERCENT, PAR_ESQ, PAR_DIR, PR_PTVIRGULA, CHAVE_ESQ,
	CHAVE_DIR, OP_DIFERENTE, OP_MENORIGUAL, OP_MAIORIGUAL,
	ASPAS,ASPASIMPLES,COMENTARIO_SIMPLES
	
}
