package Analisador;

public enum Token {
	ERROR,ID,NUMERO,SIMBOLO_ESPECIAL
	,OP_RELACIONAL,OP_ARITMETICO,
	NUMERO_DECIMAL,OP_LOGICO_OR,
	OP_LOGICO_AND,OP_LOGICO_NOT,
	COMENTARIO,OP_ATRIBUICAO, 
	PR_IF,PR_INT,
	PR_VAR,PR_ELSE,
	PR_CHAR,PR_VOID,PR_PRNT,
	PR_PROC,PR_FLOAT,
	PR_WHILE,PR_RETURN, LINHA
}
